package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	private short idactividad;
	private String nombre;
	private String lugar;
	private String categoria;
	private Set<Socio> socios = new HashSet<Socio>(0);

	public Actividad() {
	}

	public Actividad(short idactividad, String nombre, String lugar,
			String categoria) {
		this.idactividad = idactividad;
		this.nombre = nombre;
		this.lugar = lugar;
		this.categoria = categoria;
	}

	public Actividad(short idactividad, String nombre, String lugar,
			String categoria, Set<Socio> socios) {
		this.idactividad = idactividad;
		this.nombre = nombre;
		this.lugar = lugar;
		this.categoria = categoria;
		this.socios = socios;
	}

	public short getIdactividad() {
		return this.idactividad;
	}

	public void setIdactividad(short idactividad) {
		this.idactividad = idactividad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Set<Socio> getSocios() {
		return this.socios;
	}

	public void setSocios(Set<Socio> socios) {
		this.socios = socios;
	}

}
