package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	private ObjectProperty<Short> idactividad = new SimpleObjectProperty<>();
	private StringProperty nombre = new SimpleStringProperty();
	private StringProperty lugar = new SimpleStringProperty();
	private StringProperty categoria = new SimpleStringProperty();
	private Set<Socio> socios = new HashSet<Socio>(0);

	public Actividad() {
	}

	public Actividad(Short idactividad, String nombre, String lugar,
			String categoria) {
		this.idactividad.set(idactividad);
		this.nombre.set(nombre);
		this.lugar.set(lugar);
		this.categoria .set(categoria);
	}

	public Actividad(Short idactividad, String nombre, String lugar,
			String categoria, Set<Socio> socios) {
		this.idactividad.set(idactividad);
		this.nombre.set(nombre);
		this.lugar.set(lugar);
		this.categoria.set(categoria);
		this.socios = socios;
	}

	public Short getIdactividad() {
		return this.idactividad.get();
	}

	public void setIdactividad(Short idactividad) {
		this.idactividad.set(idactividad);
	}
	
	public ObjectProperty<Short> idactividadProperty(){
		return idactividad;
	}

	public String getNombre() {
		return this.nombre.get();
	}

	public void setNombre(String nombre) {
		this.nombre.set(nombre);
	}

	public StringProperty nombreProperty(){
		return nombre;
	}
	
	public String getLugar() {
		return this.lugar.get();
	}

	public void setLugar(String lugar) {
		this.lugar.set(lugar);
	}
	
	public StringProperty lugarProperty(){
		return lugar;
	}

	public String getCategoria() {
		return this.categoria.get();
	}

	public void setCategoria(String categoria) {
		this.categoria.set(categoria);
	}
	
	public StringProperty categoriaProperty(){
		return categoria;
	}

	public Set<Socio> getSocios() {
		return this.socios;
	}

	public void setSocios(Set<Socio> socios) {
		this.socios = socios;
	}
	
	@Override
	public String toString() {
		return nombre.get();
	}

}
