package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Empleo generated by hbm2java
 */
public class Empleo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ObjectProperty<Short> idempleo = new SimpleObjectProperty<>();
	private StringProperty nombre = new SimpleStringProperty();
	private StringProperty horario = new SimpleStringProperty();
	private ObjectProperty<BigDecimal> sueldo = new SimpleObjectProperty<>();
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Empleo() {
	}

	public Empleo(short idempleo, String nombre, String horario) {
		this.idempleo.set(idempleo);
		this.nombre.set(nombre);
		this.horario.set(horario);
	}

	public Empleo(short idempleo, String nombre, String horario,
			BigDecimal sueldo, Set<Empleado> empleados) {
		this.idempleo.set(idempleo);
		this.nombre.set(nombre);
		this.horario.set(horario);
		this.sueldo.set(sueldo);
		this.empleados = empleados;
	}

	public Short getIdempleo() {
		return this.idempleo.get();
	}

	public void setIdempleo(short idempleo) {
		this.idempleo.set(idempleo);
	}
	
	public ObjectProperty<Short> idempleoProperty(){
		return idempleo;
	}

	public String getNombre() {
		return this.nombre.get();
	}

	public void setNombre(String nombre) {
		this.nombre.set(nombre);
	}
	
	public StringProperty nombreProperty(){
		return nombre;
	}

	public String getHorario() {
		return this.horario.get();
	}

	public void setHorario(String horario) {
		this.horario.set(horario);
	}
	
	public StringProperty horarioProperty(){
		return horario;
	}

	public BigDecimal getSueldo() {
		return this.sueldo.get();
	}

	public void setSueldo(BigDecimal sueldo) {
		this.sueldo.set(sueldo);
	}

	public ObjectProperty<BigDecimal> sueldoProperty(){
		return sueldo;
	}
	
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}
	
	@Override
	public String toString() {
		return nombre.get();
	}

}
