package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ObjectProperty<Short> idempleado = new SimpleObjectProperty<>();
	private ObjectProperty<Empleo> empleo = new SimpleObjectProperty<>();
	private StringProperty dni = new SimpleStringProperty();
	private StringProperty nombre = new SimpleStringProperty();
	private StringProperty apellidos = new SimpleStringProperty();
	private ObjectProperty<BigDecimal> datostarjeta = new SimpleObjectProperty<>();

	public Empleado() {
	}

	public Empleado(short idempleado, Empleo empleo, String dni, String nombre,
			String apellidos, BigDecimal datostarjeta) {
		this.idempleado.set(idempleado);
		this.empleo.set(empleo);
		this.dni.set(dni);
		this.nombre.set(nombre);
		this.apellidos.set(apellidos);
		this.datostarjeta.set(datostarjeta);
	}

	public Short getIdempleado() {
		return this.idempleado.get();
	}

	public void setIdempleado(Short idempleado) {
		this.idempleado.set(idempleado);
	}
	
	public ObjectProperty<Short> idempleadoProperty(){
		return idempleado;
	}

	public Empleo getEmpleo() {
		return this.empleo.get();
	}

	public void setEmpleo(Empleo empleo) {
		this.empleo.set(empleo);
	}

	public ObjectProperty<Empleo> empleoProperty(){
		return empleo;
	}
	
	public String getDni() {
		return this.dni.get();
	}

	public void setDni(String dni) {
		this.dni.set(dni);
	}

	public StringProperty dniProperty(){
		return dni;
	}
	
	public String getNombre() {
		return this.nombre.get();
	}

	public void setNombre(String nombre) {
		this.nombre.set(nombre);
	}
	
	public StringProperty nombreProperty(){
		return nombre;
	}

	public String getApellidos() {
		return this.apellidos.get();
	}

	public void setApellidos(String apellidos) {
		this.apellidos.set(apellidos);
	}

	public StringProperty apellidosProperty(){
		return apellidos;
	}
	
	public BigDecimal getDatostarjeta() {
		return this.datostarjeta.get();
	}

	public void setDatostarjeta(BigDecimal datostarjeta) {
		this.datostarjeta.set(datostarjeta);
	}
	
	public ObjectProperty<BigDecimal> datostarjetaProperty(){
		return datostarjeta;
	}
	
	@Override
	public String toString() {
		return apellidos.get() + ", " + nombre.get();
	}

}
