package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private short idempleado;
	private Empleo empleo;
	private String dni;
	private String nombre;
	private String apellidos;
	private BigDecimal datostarjeta;

	public Empleado() {
	}

	public Empleado(short idempleado, Empleo empleo, String dni, String nombre,
			String apellidos, BigDecimal datostarjeta) {
		this.idempleado = idempleado;
		this.empleo = empleo;
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.datostarjeta = datostarjeta;
	}

	public short getIdempleado() {
		return this.idempleado;
	}

	public void setIdempleado(short idempleado) {
		this.idempleado = idempleado;
	}

	public Empleo getEmpleo() {
		return this.empleo;
	}

	public void setEmpleo(Empleo empleo) {
		this.empleo = empleo;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public BigDecimal getDatostarjeta() {
		return this.datostarjeta;
	}

	public void setDatostarjeta(BigDecimal datostarjeta) {
		this.datostarjeta = datostarjeta;
	}

}
