package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Entrada generated by hbm2java
 */
public class Entrada implements java.io.Serializable {

	private short identrada;
	private Socio socio;
	private Date fecha;

	public Entrada() {
	}

	public Entrada(short identrada, Socio socio) {
		this.identrada = identrada;
		this.socio = socio;
	}

	public Entrada(short identrada, Socio socio, Date fecha) {
		this.identrada = identrada;
		this.socio = socio;
		this.fecha = fecha;
	}

	public short getIdentrada() {
		return this.identrada;
	}

	public void setIdentrada(short identrada) {
		this.identrada = identrada;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
