package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * Entrada generated by hbm2java
 */
public class Entrada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ObjectProperty<Short> identrada = new SimpleObjectProperty<>();
	private ObjectProperty<Socio> socio = new SimpleObjectProperty<>();
	private ObjectProperty<Date> fecha = new SimpleObjectProperty<>();

	public Entrada() {
	}

	public Entrada(Short identrada, Socio socio) {
		this.identrada.set(identrada);
		this.socio.set(socio);
	}

	public Entrada(Short identrada, Socio socio, Date fecha) {
		this.identrada.set(identrada);
		this.socio.set(socio);
		this.fecha.set(fecha);
	}

	public Short getIdentrada() {
		return this.identrada.get();
	}

	public void setIdentrada(Short identrada) {
		this.identrada.set(identrada);
	}
	
	public ObjectProperty<Short> identradaProperty(){
		return identrada;
	}

	public Socio getSocio() {
		return this.socio.get();
	}

	public void setSocio(Socio socio) {
		this.socio.set(socio);
	}
	
	public ObjectProperty<Socio> socioProperty(){
		return socio;
	}

	public Date getFecha() {
		return this.fecha.get();
	}

	public void setFecha(Date fecha) {
		this.fecha.set(fecha);
	}

	public ObjectProperty<Date> fechaProperty(){
		return fecha;
	}
	
	@Override
	public String toString() {
		return socio.get() + ": " + fecha.get();
	}
}
