package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

/**
 * Personalexterno generated by hbm2java
 */
public class Personalexterno implements java.io.Serializable {

	private short idpersonalexterno;
	private String nombre;
	private String apellidos;
	private String empleo;
	private String empresa;

	public Personalexterno() {
	}

	public Personalexterno(short idpersonalexterno, String nombre,
			String apellidos, String empleo, String empresa) {
		this.idpersonalexterno = idpersonalexterno;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.empleo = empleo;
		this.empresa = empresa;
	}

	public short getIdpersonalexterno() {
		return this.idpersonalexterno;
	}

	public void setIdpersonalexterno(short idpersonalexterno) {
		this.idpersonalexterno = idpersonalexterno;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEmpleo() {
		return this.empleo;
	}

	public void setEmpleo(String empleo) {
		this.empleo = empleo;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

}
