package dam.gestorclub.entidades;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

/**
 * Personalexterno generated by hbm2java
 */
public class Personalexterno implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ObjectProperty<Short> idpersonalexterno = new SimpleObjectProperty<>();
	private StringProperty nombre = new SimpleStringProperty();
	private StringProperty apellidos = new SimpleStringProperty();
	private StringProperty empleo = new SimpleStringProperty();
	private StringProperty empresa = new SimpleStringProperty();

	public Personalexterno() {
	}

	public Personalexterno(Short idpersonalexterno, String nombre,
			String apellidos, String empleo, String empresa) {
		this.idpersonalexterno.set(idpersonalexterno);
		this.nombre.set(nombre);
		this.apellidos.set(apellidos);
		this.empleo.set(empleo);
		this.empresa.set(empresa);
	}

	public Short getIdpersonalexterno() {
		return this.idpersonalexterno.get();
	}

	public void setIdpersonalexterno(Short idpersonalexterno) {
		this.idpersonalexterno.set(idpersonalexterno);
	}
	
	public ObjectProperty<Short> idpersonalexternoProperty(){
		return idpersonalexterno;
	}

	public String getNombre() {
		return this.nombre.get();
	}

	public void setNombre(String nombre) {
		this.nombre.set(nombre);
	}

	public StringProperty nombreProperty(){
		return nombre;
	}
	
	public String getApellidos() {
		return this.apellidos.get();
	}

	public void setApellidos(String apellidos) {
		this.apellidos.set(apellidos);
	}
	
	public StringProperty apellidosProperty(){
		return apellidos;
	}

	public String getEmpleo() {
		return this.empleo.get();
	}

	public void setEmpleo(String empleo) {
		this.empleo.set(empleo);
	}
	
	public StringProperty empleoProperty(){
		return empleo;
	}

	public String getEmpresa() {
		return this.empresa.get();
	}

	public void setEmpresa(String empresa) {
		this.empresa.set(empresa);
	}
	
	public StringProperty empresaProperty(){
		return empresa;
	}
	
	@Override
	public String toString() {
		return apellidos.get() + " ," + nombre.get();
	}

}
