package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pista generated by hbm2java
 */
public class Pista implements java.io.Serializable {

	private short idpista;
	private String nombre;
	private BigDecimal precionosocios;
	private BigDecimal preciosocios;
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Pista() {
	}

	public Pista(short idpista) {
		this.idpista = idpista;
	}

	public Pista(short idpista, String nombre, BigDecimal precionosocios,
			BigDecimal preciosocios, Set<Reserva> reservas) {
		this.idpista = idpista;
		this.nombre = nombre;
		this.precionosocios = precionosocios;
		this.preciosocios = preciosocios;
		this.reservas = reservas;
	}

	public short getIdpista() {
		return this.idpista;
	}

	public void setIdpista(short idpista) {
		this.idpista = idpista;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecionosocios() {
		return this.precionosocios;
	}

	public void setPrecionosocios(BigDecimal precionosocios) {
		this.precionosocios = precionosocios;
	}

	public BigDecimal getPreciosocios() {
		return this.preciosocios;
	}

	public void setPreciosocios(BigDecimal preciosocios) {
		this.preciosocios = preciosocios;
	}

	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
