package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import net.sf.jasperreports.crosstabs.fill.JRPercentageCalculatorFactory.BigDecimalPercentageCalculator;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Pista generated by hbm2java
 */
public class Pista implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ObjectProperty<Short> idpista = new SimpleObjectProperty<>();
	private StringProperty nombre= new SimpleStringProperty();
	private ObjectProperty<BigDecimal> precionosocios = new SimpleObjectProperty<>();
	private ObjectProperty<BigDecimal> preciosocios = new SimpleObjectProperty<>();
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	
	
	public Pista() {
	}

	public Pista(short idpista) {
		this.idpista.set(idpista);
	}

	public Pista(short idpista, String nombre, BigDecimal precionosocios,
			BigDecimal preciosocios, Set<Reserva> reservas) {
		this.idpista.set(idpista);
		this.nombre.set(nombre);
		this.precionosocios.set(precionosocios);
		this.preciosocios.set(preciosocios);
		this.reservas = reservas;
	}

	public short getIdpista() {
		return this.idpista.get();
	}

	public void setIdpista(short idpista) {
		this.idpista.set(idpista);
	}
	
	public ObjectProperty<Short> idpistaProperty(){
		return idpista;
	}

	public String getNombre() {
		return nombre.get();
	}

	public void setNombre(String nombre) {
		this.nombre.set(nombre);
	}

	public StringProperty nombreProperty(){
		return nombre;
	}
	
	public BigDecimal getPrecionosocios() {
		return precionosocios.get();
	}

	public void setPrecionosocios(BigDecimal precionosocios) {
		this.precionosocios.set(precionosocios);
	}
	
	public ObjectProperty<BigDecimal> precionosociosProperty(){
		return precionosocios;
	}

	public BigDecimal getPreciosocios() {
		return this.preciosocios.get();
	}

	public void setPreciosocios(BigDecimal preciosocios) {
		this.preciosocios.set(preciosocios);
	}
	
	public ObjectProperty<BigDecimal> preciosociosProperty(){
		return preciosocios;
	}

	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
