package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

	private ReservaId id;
	private Pista pista;
	private Socio socio;
	private BigDecimal precio;
	private char estapagado;

	public Reserva() {
	}

	public Reserva(ReservaId id, Pista pista, BigDecimal precio, char estapagado) {
		this.id = id;
		this.pista = pista;
		this.precio = precio;
		this.estapagado = estapagado;
	}

	public Reserva(ReservaId id, Pista pista, Socio socio, BigDecimal precio,
			char estapagado) {
		this.id = id;
		this.pista = pista;
		this.socio = socio;
		this.precio = precio;
		this.estapagado = estapagado;
	}

	public ReservaId getId() {
		return this.id;
	}

	public void setId(ReservaId id) {
		this.id = id;
	}

	public Pista getPista() {
		return this.pista;
	}

	public void setPista(Pista pista) {
		this.pista = pista;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public char getEstapagado() {
		return this.estapagado;
	}

	public void setEstapagado(char estapagado) {
		this.estapagado = estapagado;
	}

}
