package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * ReservaId generated by hbm2java
 */
public class ReservaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ObjectProperty<Short> pistaId = new SimpleObjectProperty<>();
	private ObjectProperty<Date> fecha = new SimpleObjectProperty<>();

	public ReservaId() {
	}

	public ReservaId(short pistaId, Date fecha) {
		this.pistaId.set(pistaId);
		this.fecha.set(fecha);
	}

	public Short getPistaId() {
		return this.pistaId.get();
	}

	public void setPistaId(short pistaId) {
		this.pistaId.set(pistaId);
	}

	public Date getFecha() {
		return this.fecha.get();
	}

	public void setFecha(Date fecha) {
		this.fecha.set(fecha);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservaId))
			return false;
		ReservaId castOther = (ReservaId) other;

		return (this.getPistaId() == castOther.getPistaId())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPistaId();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return pistaId.get() + ": " + fecha.get();
	}
	
}
