package dam.gestorclub.entidades;

// Generated 16-mar-2013 16:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ObjectProperty<Short> idsocio = new SimpleObjectProperty<>();
	private StringProperty dni = new SimpleStringProperty();
	private StringProperty nombre = new SimpleStringProperty();;
	private StringProperty apellidos = new SimpleStringProperty();;
	private StringProperty correo = new SimpleStringProperty();;
	private ObjectProperty<Character> esvaron = new SimpleObjectProperty<>();
	private StringProperty telefono = new SimpleStringProperty();;
	private StringProperty direccion = new SimpleStringProperty();;
	private ObjectProperty<Date> fechanac = new SimpleObjectProperty<>();
	private ObjectProperty<BigDecimal> cuentabancaria = new SimpleObjectProperty<>();
	private ObjectProperty<BigDecimal> codigobarras = new SimpleObjectProperty<>();
	private ObjectProperty<Short> descuento = new SimpleObjectProperty<>();
	private Set<Reserva> reservas = new HashSet<Reserva>(0);
	private Set<Actividad> actividads = new HashSet<Actividad>(0);
	private Set<Entrada> entradas = new HashSet<Entrada>(0);

	public Socio() {
	}

	public Socio(short idsocio, String dni, String nombre, String apellidos,
			String correo, char esvaron, String telefono, String direccion) {
		this.idsocio.set(idsocio);
		this.dni.set(dni);
		this.nombre.set(nombre);
		this.apellidos.set(apellidos);
		this.correo.set(correo);
		this.esvaron.set(esvaron);
		this.telefono.set(telefono);
		this.direccion.set(direccion);
	}

	public Socio(short idsocio, String dni, String nombre, String apellidos,
			String correo, char esvaron, String telefono, String direccion,
			Date fechanac, BigDecimal cuentabancaria, BigDecimal codigobarras,
			Short descuento, Set<Reserva> reservas, Set<Actividad> actividads,
			Set<Entrada> entradas) {
		this.idsocio.set(idsocio);
		this.dni.set(dni);
		this.nombre.set(nombre);
		this.apellidos.set(apellidos);
		this.correo.set(correo);
		this.esvaron.set(esvaron);
		this.telefono.set(telefono);
		this.direccion.set(direccion);
		this.fechanac.set(fechanac);
		this.cuentabancaria.set(cuentabancaria);
		this.codigobarras.set(codigobarras);
		this.descuento.set(descuento);
		this.reservas = reservas;
		this.actividads = actividads;
		this.entradas = entradas;
	}

	public Short getIdsocio() {
		return this.idsocio.get();
	}

	public void setIdsocio(short idsocio) {
		this.idsocio.set(idsocio);
	}
	
	public ObjectProperty<Short> idsocioProperty(){
		return idsocio;
	}

	public String getDni() {
		return this.dni.get();
	}

	public void setDni(String dni) {
		this.dni.set(dni);
	}
	
	public StringProperty dniProperty(){
		return dni;
	}

	public String getNombre() {
		return this.nombre.get();
	}

	public void setNombre(String nombre) {
		this.nombre.set(nombre);
	}
	
	public StringProperty nombreProperty(){
		return nombre;
	}

	public String getApellidos() {
		return this.apellidos.get();
	}

	public void setApellidos(String apellidos) {
		this.apellidos.set(apellidos);
	}

	public StringProperty apellidosProperty(){
		return apellidos;
	}
	
	public String getCorreo() {
		return this.correo.get();
	}

	public void setCorreo(String correo) {
		this.correo.set(correo);
	}
	
	public StringProperty correoProperty(){
		return correo;
	}

	public char getEsvaron() {
		return this.esvaron.get();
	}

	public void setEsvaron(char esvaron) {
		this.esvaron.set(esvaron);
	}
	
	public ObjectProperty<Character> esvaronProperty(){
		return esvaron;
	}

	public String getTelefono() {
		return this.telefono.get();
	}

	public void setTelefono(String telefono) {
		this.telefono.set(telefono);
	}
	
	public StringProperty telefonoProperty(){
		return telefono;
	}

	public String getDireccion() {
		return this.direccion.get();
	}

	public void setDireccion(String direccion) {
		this.direccion.set(direccion);
	}
	
	public StringProperty direccionProperty(){
		return direccion;
	}

	public Date getFechanac() {
		return this.fechanac.get();
	}

	public void setFechanac(Date fechanac) {
		this.fechanac.set(fechanac);
	}
	
	public ObjectProperty<Date> fechanacProperty(){
		return fechanac;
	}

	public BigDecimal getCuentabancaria() {
		return this.cuentabancaria.get();
	}

	public void setCuentabancaria(BigDecimal cuentabancaria) {
		this.cuentabancaria.set(cuentabancaria);
	}

	public ObjectProperty<BigDecimal> cuentabancariaProperty(){
		return cuentabancaria;
	}
	
	public BigDecimal getCodigobarras() {
		return this.codigobarras.get();
	}

	public void setCodigobarras(BigDecimal codigobarras) {
		this.codigobarras.set(codigobarras);
	}

	public ObjectProperty<BigDecimal> codigobarrasProperty(){
		return codigobarras;
	}
	
	public Short getDescuento() {
		return this.descuento.get();
	}

	public void setDescuento(Short descuento) {
		this.descuento.set(descuento);
	}
	
	public ObjectProperty<Short> descuentoProperty(){
		return descuento;
	}

	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

	public Set<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(Set<Actividad> actividads) {
		this.actividads = actividads;
	}

	public Set<Entrada> getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set<Entrada> entradas) {
		this.entradas = entradas;
	}

}
